mv agencyCorrespondenceAdmin.groovy agencyCorrespondenceAdminJobs.groovy
mv Claims.groovy ClaimsJobs.groovy
mv CommonUIWeb.groovy CommonUIWebJobs.groovy
mv CTCT.groovy CTCTJobs.groovy
mv Dividends.groovy DividendsJobs.groovy
mv docDataServices.groovy docDataServicesJobs.groovy
mv dynamicContent.groovy dynamicContentJobs.groovy
mv eBizLite.groovy eBizLiteJobs.groovy
mv eFROI.groovy eFROIJobs.groovy
mv Endorsements.groovy EndorsementsJobs.groovy
mv Favor.groovy FavorJobs.groovy
mv GatewayWeb.groovy GatewayWebJobs.groovy
mv LossRun.groovy LossRunJobs.groovy
mv OIR.groovy OIRJobs.groovy
mv OnlineEob.groovy OnlineEobJobs.groovy
mv OnlineReporting.groovy OnlineReportingJobs.groovy
mv Payments.groovy PaymentsJobs.groovy
mv Safety.groovy SafetyJobs.groovy
mv SafetyLite.groovy SafetyLiteJobs.groovy
mv SafetySrvcs.groovy SafetySrvcsJobs.groovy
mv SF_TMI_IWCS_AvayaOD_Application.groovy SF_TMI_IWCS_AvayaOD_ApplicationJobs.groovy
mv TempUser.groovy TempUserJobs.groovy
mv tmoAdmin.groovy tmoAdminJobs.groovy
mv tmoDataServices.groovy tmoDataServicesJobs.groovy
mv TMODocuments.groovy TMODocumentsJobs.groovy
mv tmopolicy.groovy tmopolicyJobs.groovy
mv tmoSelfAdmin.groovy tmoSelfAdminJobs.groovy
mv tmoSelfEnrollment.groovy tmoSelfEnrollmentJobs.groovy
mv TMOSharedWeb.groovy TMOSharedWebJobs.groovy
mv txmApi.groovy txmApiJobs.groovy
mv txmDoc.groovy txmDocJobs.groovy
mv x.sh x.shJobs.groovy
