#!/bin/sh

sed -i s^folder\(^multiJob\(^g ./DocMgmts/AuditJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/CMUJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/DAFIJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/DocAssemblyJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/EIReportingJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/EcViewerJobs.groovy
sed -i s^folder\(^multiJob\(^g ./DocMgmts/eStampAppJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/AISJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/AgMSJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/AgencyBillJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/BRSBalRptJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/ClientJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/DeductibleJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/DirectBillJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/FinancialToolsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/InstallmentsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/OtherStatesJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/QACJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/SecMaintJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/SecRuntimeJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Finappss/UCSDaemonJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Intranet/AWWJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Intranet/ClaimViewerJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Intranet/FormAndBatchViewerJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Intranet/NetworkOwnershipJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Other/ccwikiJobs.groovy
sed -i s^folder\(^multiJob\(^g ./Other/iscwikiJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/CDSJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/InterimAuditReportingJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/MasterAgentCommissionJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/PABSPolicyRptgJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/PolRptBalanceCntrlJobs.groovy
sed -i s^folder\(^multiJob\(^g ./UWApps/UnitStatJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/CTCTJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/ClaimsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/CommonUIWebJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/DividendsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/EndorsementsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/FavorJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/GatewayWebJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/LossRunJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/OIRJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/OnlineEobJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/OnlineReportingJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/PaymentsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/SF_TMI_IWCS_AvayaOD_ApplicationJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/SafetyJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/SafetyLiteJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/SafetySrvcsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/TMODocumentsJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/TMOSharedWebJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/TempUserJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/agencyCorrespondenceAdminJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/docDataServicesJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/dynamicContentJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/eBizLiteJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/eFROIJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/tmoAdminJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/tmoDataServicesJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/tmoSelfAdminJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/tmoSelfEnrollmentJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/tmopolicyJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/txmApiJobs.groovy
sed -i s^folder\(^multiJob\(^g ./tmoApps/txmDocJobs.groovy
